name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'バージョン'
env:
  IMAGE_NAME: 'gha-image'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - use: actions/checkout@v4
      - use: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - use: docker/meta-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=${{version}},value=${{ inputs.version }}
            type=raw,value=latest
      - use: docker/build-push-action@v5
        with:
          push: true
          context: docker/example
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
